const ACCESS_ID = "ACCESS_KEY"
const SECRET_ACCESS_KEY = "ACCESS_SECRET_KEY"
const AWS_REGION = "REGION"

const BUCKET_NAME = "BUCKET_NAME"
const CLOUDFRONT_URL = "CLOUDFRONT_URL"

module.exports = {
    ACCESS_ID,
    SECRET_ACCESS_KEY,
    AWS_REGION,
    BUCKET_NAME,
    CLOUDFRONT_URL
}
